services:
  webserver:
    image: ghcr.io/phppdf/docker-image-php-apache:dev
    build:
      context: .
      dockerfile: .docker/webserver/Dockerfile
    container_name: phppdf
    user: app
    volumes:
      - ./:/opt/app/

  hugo:
    build:
      context: .
      dockerfile: .docker/hugo/Dockerfile
    container_name: phppdf-hugo
    volumes:
      - ./:/src
    ports:
      - "1313:1313"
